export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
//export const FILTER_QUESTIONS = 'FILTER_QUESTIONS';
//export const CLEAR_FILTER_QUESTION = 'CLEAR_FILTER_QUESTION';
export const QUESTION_ERROR = 'QUESTION_ERROR';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


export const ADD_QUIZ = 'ADD_QUIZ';
export const CLEAR_FILTER_QUIZ = 'CLEAR_FILTER_QUIZ';
//export const DELETE_QUIZ_TITLE = DELETE_QUIZ_TITLE;
//export const UPDATE_QUIZ_TITLE = UPDATE_QUIZ_TITLE;
export const QUIZ_ERROR = 'QUIZ_ERROR';
export const FILTER_QUIZZES = 'FILTER_QUIZZES';





